### ISSUE TITLE
Ablanor på NHN

### ISSUE THREAD

**Issue by arnfinn** [Rapporteket/ablanor#49]
Få Ablanor til å kjøre på NHN (i QA).

Falk og q8s-oppføring er OK.

## TODO

- [x] #50
- [x] Lag docker-image og dytt det opp til Harbor
- [x] Endre i oppføringen i `values.yaml`-fila (se under)

```yml
apps:
- id: ablanor
  name: Nasjonalt register for ablasjonsbehandling og elektrofysiologi i Norge - AblaNor
  autoreport:
    enabled: false
    cron: 0 3 * * *
  description: Rapportek-applikasjon for OpenQReg-registeret Nasjonalt register for ablasjonsbehandling og elektrofysiologi i Norge - AblaNor.
  falkAppId: 93
  image: ablanor:0.0.0 # TODO set tag
  cmd: ["R", "-e", "options(shiny.port=3838); options(shiny.host='0.0.0.0'); TODO_ADD_CMD"] # TODO add cmd
  secrets:
    - ablanor
    - mysql
```
